datasets:
# Classification (17 datasets, 665,730 samples)
- dataset_sample: all
  json_path: ./2D_Task/APTOS/APTOS_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/BloodMNIST/BloodMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Brain_Tumor_MRI/Brain_Tumor_MRI_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ChestMNIST/ChestMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/DermaMNIST/DermaMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ISIC_2019/ISIC_2019_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Kvasir/Kvasir_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OCTMNIST/OCTMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganAMNIST/OrganAMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganCMNIST/OrganCMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganSMNIST/OrganSMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PathMNIST/PathMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/TissueMNIST/TissueMNIST_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/MIMIC-CXR-T/mimic-cxr-lt-train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PanNuke/pannuke_train.jsonl
# Classification I2I (17 datasets, 665,730 samples)
- dataset_sample: all
  json_path: ./2D_Task/APTOS/APTOS_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/BloodMNIST/BloodMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Brain_Tumor_MRI/Brain_Tumor_MRI_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ChestMNIST/ChestMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/DermaMNIST/DermaMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ISIC_2019/ISIC_2019_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Kvasir/Kvasir_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OCTMNIST/OCTMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganAMNIST/OrganAMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganCMNIST/OrganCMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganSMNIST/OrganSMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PathMNIST/PathMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/TissueMNIST/TissueMNIST_i2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/MIMIC-CXR-T/mimic-cxr-lt-i2i-train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PanNuke/pannuke_i2i_train.jsonl
# Classification T2I (17 datasets, 665,730 samples)
- dataset_sample: all
  json_path: ./2D_Task/APTOS/APTOS_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/BloodMNIST/BloodMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Brain_Tumor_MRI/Brain_Tumor_MRI_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ChestMNIST/ChestMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/DermaMNIST/DermaMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ISIC_2019/ISIC_2019_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Kvasir/Kvasir_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OCTMNIST/OCTMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganAMNIST/OrganAMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganCMNIST/OrganCMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/OrganSMNIST/OrganSMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PathMNIST/PathMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/TissueMNIST/TissueMNIST_t2i_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/MIMIC-CXR-T/mimic-cxr-lt-t2i-train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PanNuke/pannuke_t2i_train.jsonl
# VQA (8 datasets, 529,444 samples)
- dataset_sample: all
  json_path: ./2D_Task/MedPIX/MedPix_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/MIMIC-CXR-VQA/mimic_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PathVQA/Path-VQA_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PMC/PMC-VQA_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/RadImageNet-VQA/RadLmageNet_train_sampled.jsonl
- dataset_sample: all
  json_path: ./2D_Task/ROCO-VQA/ROCO_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/VQA-RAD/VQA_train.jsonl
# 3D CT Rate (5 datasets, 100,125 samples)
- dataset_sample: all
  json_path: ./3D_Task/CT_RATE/CT_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/CT_RATE/CT_i2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/CT_RATE/CT_t2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/CT_RATE/CT_vqa_train.jsonl
# 3D Classification (5 datasets, 4,650 samples)
- dataset_sample: all
  json_path: ./3D_Task/ChirrMRI600/Chirr_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/MRNet/MRNet_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/NoduleMNIST/Nodule_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/Organ3dMNIST/Organ_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/SynapseMNIST/Synapse_train.jsonl
# 3D Classification I2I (3 datasets, 2,262 samples)
- dataset_sample: all
  json_path: ./3D_Task/ChirrMRI600/Chirr_i2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/MRNet/MRNet_i2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/Organ3dMNIST/Organ_i2i_train.jsonl
# 3D Classification T2I (3 datasets, 2,262 samples)
- dataset_sample: all
  json_path: ./3D_Task/ChirrMRI600/Chirr_t2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/MRNet/MRNet_t2i_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/Organ3dMNIST/Organ_t2i_train.jsonl
# RadGen-CT (3 datasets, 128,729 samples)
- dataset_sample: all
  json_path: ./3D_Task/RadGen_CT/RGCC_i2t_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/RadGen_CT/RGCC_train_VQA.jsonl
# M3D (3 datasets, 591,017 samples)
- dataset_sample: all
  json_path: ./3D_Task/M3D/m3d_3dqa_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/M3D/m3d_i2t_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/M3D/m3d_t2i_train.jsonl
# Text-to-Text (4 datasets, 465,567 samples)
- dataset_sample: all
  json_path: ./Text_Task/MIMIC_f2i_train.jsonl
- dataset_sample: all
  json_path: ./Text_Task/Med_Embeds_train.jsonl
- dataset_sample: all
  json_path: ./Text_Task/medmcqa_train.jsonl
- dataset_sample: all
  json_path: ./Text_Task/PubMedQA_train.jsonl
- dataset_sample: all
  json_path: ./Text_Task/MMDental_t2t_train.jsonl
# 3D Task (6 datasets, 1,497 samples)
- dataset_sample: all
  json_path: ./3D_Task/MMDental/MMDental_i2t_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/SynthRAD/brain_ct_to_mri_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/SynthRAD/brain_mri_to_ct_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/SynthRAD/pelvis_ct_to_mri_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/SynthRAD/pelvis_mri_to_ct_train.jsonl
# 3D2Text & Cross-modal (7 datasets, 5,954 samples)
- dataset_sample: all
  json_path: ./3D_Task/BraTS2023/bratsped_t1_to_t2_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/BraTS2023/bratsped_t2_to_t1_train.jsonl
- dataset_sample: all
  json_path: ./3D_Task/CirrMRI600_Cross/ChirrMRI_train_t1_to_t2.jsonl
- dataset_sample: all
  json_path: ./3D_Task/CirrMRI600_Cross/ChirrMRI_train_t2_to_t1.jsonl
- dataset_sample: all
  json_path: ./3D_Task/HaN-Seg/hanseg_mri_to_ct_train.jsonl
# Report Generation (2 datasets, 275,922 samples)
- dataset_sample: all
  json_path: ./2D_Task/MIMIC-CXR-Report/MIMIC-CXR_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/USData/USData_train.jsonl
# Visual Grounding 1 (4 datasets, 44,626 samples)
- dataset_sample: all
  json_path: ./2D_Task/ChestImagrome/Chest_imagenome_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/VinDrCXR/VinDr-CXR_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/SkinLesion/skin_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/VindrMammo/VindrMammo_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/Gastrointestinal/gastrointestinal_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/PanNuke_VG/PanNuke_train.jsonl
- dataset_sample: all
  json_path: ./2D_Task/UltrasoundNerve/Ultrasound_train.jsonl
